// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfjYOvgypJxCUFMDqw_OSdF_BusG9h40',
    appId: '1:455371771890:web:6b14943123d8abc69f256b',
    messagingSenderId: '455371771890',
    projectId: 'tp-dap-522a9',
    authDomain: 'tp-dap-522a9.firebaseapp.com',
    storageBucket: 'tp-dap-522a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDa_s-gUEPOXQs15QJ-fwbfxirL75Ufsk',
    appId: '1:455371771890:android:a50a8f412a35af0d9f256b',
    messagingSenderId: '455371771890',
    projectId: 'tp-dap-522a9',
    storageBucket: 'tp-dap-522a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBeYBWekzg76y3hHtbOe4rUKGJGWAvjE',
    appId: '1:455371771890:ios:35f1c67931109a159f256b',
    messagingSenderId: '455371771890',
    projectId: 'tp-dap-522a9',
    storageBucket: 'tp-dap-522a9.firebasestorage.app',
    iosBundleId: 'com.example.clase184',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVBeYBWekzg76y3hHtbOe4rUKGJGWAvjE',
    appId: '1:455371771890:ios:35f1c67931109a159f256b',
    messagingSenderId: '455371771890',
    projectId: 'tp-dap-522a9',
    storageBucket: 'tp-dap-522a9.firebasestorage.app',
    iosBundleId: 'com.example.clase184',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfjYOvgypJxCUFMDqw_OSdF_BusG9h40',
    appId: '1:455371771890:web:3544392c480aeb669f256b',
    messagingSenderId: '455371771890',
    projectId: 'tp-dap-522a9',
    authDomain: 'tp-dap-522a9.firebaseapp.com',
    storageBucket: 'tp-dap-522a9.firebasestorage.app',
  );

}